services:
  - type: web
    name: krealgram-backend
    env: node
    plan: free
    region: frankfurt
    buildCommand: "chmod +x install.sh && ./install.sh && cd backend && npm install"
    startCommand: "cd backend && node index.js"
    envVars:
      - fromGroup: Krealgram
      - key: CHROME_BIN
        value: /usr/bin/google-chrome-stable
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true