services:
  - type: web
    name: krealgram-backend
    env: node
    plan: free
    region: frankfurt
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && node index-simple.js"
    envVars:
      - fromGroup: Krealgram
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false