services:
  - type: web
    name: krealgram-backend
    env: node
    region: frankfurt
    plan: starter
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_OPTIONS
        value: "--max_old_space_size=460"
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /health
    autoDeploy: false