services:
  - type: web
    name: krealgram-backend
    env: node
    plan: free
    region: frankfurt
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && node index.js"
    envVars:
      - fromGroup: Krealgram